const common = [
  require("../images/bingo-bg.svg"),
  require("../images/bingo-fail.svg"),
  require("../images/bingo-finish-plate.svg"),
  require("../images/bingo-finish-plate-mob.svg"),
  require("../images/bingo-img.png"),
  require("../images/bingo-img-mob.png"),
  require("../images/bingo-lights-phase1.svg"),
  require("../images/bingo-lights-phase2.svg"),
  require("../images/bingo-plate.svg"),
  require("../images/bingo-plate-game.svg"),
  require("../images/bingo-plate-game-mob.svg"),
  require("../images/bingo-plate-items.svg"),
  require("../images/bingo-plate-items-game.svg"),
  require("../images/bingo-plate-items-game-mob.svg"),
  require("../images/bingo-plate-items-mob.svg"),
  require("../images/bingo-plate-mob.svg"),
  require("../images/bingo-red-stripe.svg"),
  require("../images/bingo-slot-handle.png"),
  require("../images/bingo-slot-lever.png"),
  require("../images/bingo-slot-lever-base.png"),
  require("../images/bingo-slot-machine.png"),
  require("../images/bingo-slot-overlay.svg"),
  require("../images/bingo-slot1.png"),
  require("../images/bingo-slot2.png"),
  require("../images/bingo-slot3.png"),
  require("../images/bingo-slot4.png"),
  require("../images/bingo-slot5.png"),
  require("../images/bingo-slot6.png"),
  require("../images/bingo-slot7.png"),
  require("../images/bingo-slots.png"),
  require("../images/bingo-slots2.png"),
  require("../images/bingo-slots3.png"),
  require("../images/bingo-title-bg.svg"),
  require("../images/bingo-title-bg-mobile.svg"),
  require("../images/bingo-underline.svg"),
  require("../images/bingo-win-item-left.svg"),
  require("../images/bingo-win-item-right.svg"),
  require("../images/gift-particles/particle1.svg"),
  require("../images/gift-particles/particle10.svg"),
  require("../images/gift-particles/particle11.svg"),
  require("../images/gift-particles/particle12.svg"),
  require("../images/gift-particles/particle2.svg"),
  require("../images/gift-particles/particle3.svg"),
  require("../images/gift-particles/particle4.svg"),
  require("../images/gift-particles/particle5.svg"),
  require("../images/gift-particles/particle6.svg"),
  require("../images/gift-particles/particle7.svg"),
  require("../images/gift-particles/particle8.svg"),
  require("../images/gift-particles/particle9.svg"),
];

const resources = {
  1: [
    ...common,
    // require("../images/game1/bg.jpg"),
  ],
};

export default resources;
