const common = [
  require("../images/finish-plate.png"),
  require("../images/logo-bg.svg"),
  require("../images/score-pie.png"),
  require("../images/snow-small.png"),
  require("../images/snow1.svg"),
  require("../images/snow10.svg"),
  require("../images/snow11.svg"),
  require("../images/snow12.svg"),
  require("../images/snow2.svg"),
  require("../images/snow3.svg"),
  require("../images/snow4.svg"),
  require("../images/snow5.svg"),
  require("../images/snow6.svg"),
  require("../images/snow7.svg"),
  require("../images/snow8.svg"),
  require("../images/snow9.svg"),
  require("../images/finish-decor1.svg"),
  require("../images/finish-decor2.svg"),
  require("../images/finish-decor3.svg"),
  require("../images/finish-decor4.svg"),
  require("../images/finish-decor5.svg"),
  require("../images/score-decor1.svg"),
  require("../images/score-decor2.svg"),
  require("../images/score-decor3.svg"),
  require("../images/score-decor4.svg"),
  require("../images/score-decor5.svg"),
];

const resources = {
  1: [
    ...common,
    require("../images/game1/bg.jpg"),
    require("../images/game1/bg-mob.jpg"),
    require("../images/game1/logo.png"),
    require("../images/game1/instruction.png"),
    require("../images/game1/bg-common.jpg"),
    require("../images/game1/bg-common-mob.jpg"),
    require("../images/game1/objects/good/o1.png"),
    require("../images/game1/objects/good/o2.png"),
    require("../images/game1/objects/good/o3.png"),
    require("../images/game1/objects/good/o4.png"),
    require("../images/game1/objects/good/o5.png"),
    require("../images/game1/objects/good/o6.png"),
    require("../images/game1/objects/good/o7.png"),
    require("../images/game1/objects/good/o8.png"),
    require("../images/game1/objects/good/o9.png"),
    require("../images/game1/objects/good/o10.png"),
    require("../images/game1/objects/good/o11.png"),
    require("../images/game1/objects/good/o12.png"),
    require("../images/game1/objects/bad/o1.png"),
    require("../images/game1/objects/bad/o2.png"),
    require("../images/game1/objects/bad/o3.png"),
    require("../images/game1/objects/bad/o4.png"),
    require("../images/game1/objects/bad/o5.png"),
    require("../images/game1/objects/bad/o6.png"),
    require("../images/game1/objects/bad/o7.png"),
    require("../images/game1/objects/bad/o8.png"),
    require("../images/game1/objects/bad/o9.png"),
    require("../images/game1/objects/bad/o10.png"),
    require("../images/game1/bonus.svg"),
    require("../images/game1/bonus-display.svg"),
    require("../images/game1/head-bg.svg"),
    require("../images/game1/logo-bg.svg"),
  ],
};

export default resources;
